pennmem/cmlreaders

cmlreaders/path_finder.py

Remove print call

---

cmlreaders/path_finder.py
cmlreaders/test/conftest.py
cmlreaders/test/test_path_finder.py

Don't sort Ramulator directories by mtime

---

cmlreaders/cmlreader.py
cmlreaders/constants.py
cmlreaders/exc.py
cmlreaders/readers.py
cmlreaders/test/test_cmlreader.py

Updates to basic implementation to conform to the newly-defined API.

Api update

---

cmlreaders/cmlreader.py
cmlreaders/constants.py
cmlreaders/readers.py
cmlreaders/test/test_cmlreader.py
cmlreaders/test/test_path_finder.py
cmlreaders/test/test_readers.py

Additional reader to load the serialized classifiers

Classifier container reader

---

cmlreaders/__init__.py
cmlreaders/base_reader.py
cmlreaders/cmlreader.py
cmlreaders/exc.py
cmlreaders/readers.py
cmlreaders/readers/__init__.py
cmlreaders/readers/readers.py

Initial implementation of the readers using metaclasses to avoid needing to update the dictionary class variable in CMLReader.

Meta refactor

---

cmlreaders/base_reader.py
cmlreaders/cmlreader.py
cmlreaders/readers/eeg.py
cmlreaders/test/test_eeg.py

Integrate EEGReader with CMLReader

---

cmlreaders/readers/readers.py
cmlreaders/test/test_eeg.py
cmlreaders/test/test_readers.py

Previously this was using the generic JSON reader, but that results in a weird DataFrame. It is more sensible to just return a dict here.

Use a custom reader for sources.json

---

cmlreaders/readers/eeg.py
cmlreaders/test/test_eeg.py
cmlreaders/timeseries.py

- Fix conversion of events to epochs
- Make epochs use samples instead of milliseconds (this greatly simplifies the internal logic)

Update EEG reading

---

cmlreaders/cmlreader.py
cmlreaders/path_finder.py
cmlreaders/test/test_util.py
cmlreaders/util.py

Optionally configure rootdir with an environment variable

---

cmlreaders/readers/readers.py
cmlreaders/test/test_util.py
cmlreaders/util.py

Cherry-picked from the now-closed #51.

Add function to check if EEG data can be rereferenced

---

cmlreaders/cmlreader.py
cmlreaders/exc.py
cmlreaders/readers/eeg.py
cmlreaders/test/test_cmlreader.py
cmlreaders/test/test_eeg.py
cmlreaders/test/utils.py

Automatically determine montage/localization number when possible

---

cmlreaders/base_reader.py
cmlreaders/readers/electrodes.py
cmlreaders/test/test_readers.py

Make using specific readers easier

---

cmlreaders/data_index.py
cmlreaders/test/test_data_index.py

Coerce localization/montage numbers to integers

---

.travis.yml

Use environment variable to specify conda Python version

---

cmlreaders/test/test_readers.py

Write test output to a temporary directory

---

cmlreaders/base_reader.py
cmlreaders/cmlreader.py
cmlreaders/constants.py
cmlreaders/exc.py
cmlreaders/path_finder.py
cmlreaders/readers/__init__.py
cmlreaders/readers/electrodes.py
cmlreaders/readers/readers.py
cmlreaders/readers/reports.py
cmlreaders/test/test_cmlreader.py
cmlreaders/test/test_readers.py
cmlreaders/test/utils.py

Support multiple protocols

---

cmlreaders/cmlreader.py
cmlreaders/convert.py
cmlreaders/readers/__init__.py
cmlreaders/readers/eeg.py
cmlreaders/readers/readers.py
cmlreaders/test/test_convert.py
cmlreaders/test/test_eeg.py
docs/api.rst
docs/dev.rst

Automatically import all reader classes

---

cmlreaders/readers/__init__.py

Update magic importing of readers

---

cmlreaders/cmlreader.py
cmlreaders/test/test_cmlreader.py

Load task_events for PS2

---

cmlreaders/readers/eeg.py
cmlreaders/test/test_eeg.py

Give a better error message for no events

---

cmlreaders/cmlreader.py
cmlreaders/test/test_cmlreader.py

Read events from multiple sessions

---

cmlreaders/eeg_container.py
cmlreaders/readers/eeg.py
cmlreaders/test/test_cmlreader.py
cmlreaders/test/test_eeg.py
cmlreaders/test/test_eeg_container.py

Multisession EEG

---

cmlreaders/__init__.py
cmlreaders/_accessors/__init__.py
cmlreaders/_accessors/decorator.py
cmlreaders/_accessors/events.py
cmlreaders/test/test_accessors.py
docs/index.rst
docs/shortcuts.rst

Add shortcuts for common queries

---

cmlreaders/base_reader.py
cmlreaders/readers/eeg.py
cmlreaders/readers/electrodes.py
cmlreaders/readers/readers.py
cmlreaders/readers/reports.py
cmlreaders/test/test_readers.py

BaseCMLReader no longer searches for the path at construction

---

.gitignore
CHANGELOG.rst
cmlreaders/readers/eeg.py

Improve split EEG read speed

---

cmlreaders/constants.py
cmlreaders/readers/eeg.py

Better eeg meta

---

cmlreaders/readers/eeg.py
cmlreaders/test/test_eeg.py

Drop duplicates

---

cmlreaders/path_finder.py
cmlreaders/warnings.py
setup.cfg

Filter warnings for multiple paths found in tests

---

cmlreaders/cmlreader.py
cmlreaders/test/test_cmlreader.py

Allow passing strings to CMLReader.load_events

---

cmlreaders/constants.py
cmlreaders/path_finder.py
cmlreaders/test/test_path_finder.py

Use the most recent Ramulator directory when requesting those files

---

cmlreaders/cmlreader.py
cmlreaders/test/test_cmlreader.py

Use task_events for all PS tasks

---

cmlreaders/cmlreader.py
cmlreaders/test/test_cmlreader.py

Coerce "events" to "task_events" for TH experiments

---

cmlreaders/readers/eeg.py
cmlreaders/test/test_eeg.py
cmlreaders/warnings.py

Addresses newer subjects in #157.

Handle missing channels in Ramulator HDF5 EEG files

---

cmlreaders/cmlreader.py

Only register readers once

---

cmlreaders/eeg_container.py
cmlreaders/readers/eeg.py

Use rel_start as the start time for EEG

---

cmlreaders/cmlreader.py
cmlreaders/test/test_cmlreader.py

Add get_data_index staticmethod to CMLReader

---

cmlreaders/cmlreader.py

Load YC events

---

cmlreaders/base_reader.py
cmlreaders/readers/readers.py
cmlreaders/readers/reports.py
cmlreaders/test/test_readers.py

Remove to_xyz methods

---

cmlreaders/readers/eeg.py

Drop events with negative eegoffset

---

cmlreaders/readers/eeg.py
cmlreaders/test/data/multiNSx_sources.json
cmlreaders/test/test_eeg.py

MultiNSx sources.json

---

cmlreaders/cmlreader.py
cmlreaders/test/test_eeg.py

Fix loading of partial sessions with rel_start/rel_stop kwargs

---

cmlreaders/readers/eeg.py

Handle cases with erroneously named EEG files

---

cmlreaders/readers/eeg.py
cmlreaders/test/test_eeg.py

Negative offsets

---

cmlreaders/cmlreader.py

Add a __repr__ for CMLReader

---

cmlreaders/constants.py
cmlreaders/readers/electrodes.py
cmlreaders/readers/readers.py
cmlreaders/test/test_cmlreader.py
cmlreaders/test/test_electrode.py

Mni coords

---

cmlreaders/readers/eeg.py

Fixed broken ScalpEEGReader that was out of date with current MNE. Previously had poorly specified baseline interval that was performing a baseline average without allowing user control. Switched to loading raw data instead.

Mne updates

---

cmlreaders/cmlreader.py
cmlreaders/readers/electrodes.py

This is a super quick fix of a couple typos I noticed as I was reading / familiarizing myself with the code.

[MNT] - Fix typos

---

cmlreaders/cmlreader.py

Modify load_events to address #239

---

cmlreaders/eeg_container.py
cmlreaders/readers/eeg.py

Address #250, at least with scalp EEG. Doesn't fix #241 though.

mne doesn't allow arbitrary fields in eeg.info

---

.travis.yml
CHANGELOG.rst

Update changelog, ignore flake error for travis checks.

version 0.10.4

---

CHANGELOG.rst

Forgot to update `CHANGELOG.rst` on original v.0.10.8 release.

v0.10.8 update changelog

---

CHANGELOG.rst
cmlreaders/__init__.py
cmlreaders/readers/eeg.py

Session with multiple EEG files error on EEG boundary checks.  Toggle off those checks if multiple EEG files.

Patch EEG loading error

---

cmlreaders/readers/eeg.py

Improve error messages that raise when loading EEG beyond the boundaries of the recording.

EEG boundaries error messages
